'use strict';

/*
 *  File: Teachers.js
 *  Type: DataFixture
 *  Generated by: Mongoose-Fixture (v0.4.1)
 *
 */

// @callback must be returned
// expects (err, object)
// object can be an array of data-documents, or a kwarg['dataFixtures']
// mongoose is the instance of mongoose being used (has schemas)
// conn is the current native mongodb connection (will contain models)
module.exports = function(mongoose, conn, callback){

  // standard callback error
  var error = null;

  // create your data documents using object-literals
  var fixture = [];

  /*
   * Example of adding a data document/fixture item
  fixture.push({
      // by not defining an _id mongoose-fixture
      // will by default set a mongo ObjectID
      // defining one manually will override mongoDB
    name:'Some Test Data',
    tags:['test','data']
  });
   */

  /*
    "_id": ObjectId("53abae3773b31a0000ec912a"), // Adam
    "_id": ObjectId("53abae3773b31a0000ec9130"), // Cong
    "_id": ObjectId("53abae3773b31a0000ec9136"), // Yoav
  */

  fixture.push({
    "_id": "53abae3773b31a0000ec912a", // Adam
    "name":"Adam",
    "sex": "m",
    "dob": "1981-01-01",
    "info": "Adam loves apples.",
    "availability": [
      {
        "day": "Sun",
        "slots": [
          {
            "hh1": 10,
            "mm1": 30,
            "hh2": 11,
            "mm2": 0
          }
        ]
      },
      {
        "day": "Mon",
        "slots": [
          {
            "hh1": 10,
            "mm1": 30,
            "hh2": 12,
            "mm2": 0
          },
          {
            "hh1": 13,
            "mm1": 0,
            "hh2": 14,
            "mm2": 0,
            "mm3": 0
          }
        ]
      }
    ]
  });

  fixture.push({
    "_id": "53abae3773b31a0000ec9130", // Cong
    "name":"Cong",
    "sex": "m",
    "dob": "1983-03-23",
    "info": "Cong loves cats.",
    "availability": [
      {
        "day": "Sun",
        "slots": [
          {
            "hh1": 10,
            "mm1": 30,
            "hh2": 11,
            "mm2": 0
          }
        ]
      },
      {
        "day": "Tue",
        "slots": [
          {
            "hh1": 10,
            "mm1": 30,
            "hh2": 12,
            "mm2": 0
          },
          {
            "hh1": 13,
            "mm1": 0,
            "hh2": 14,
            "mm2": 0,
            "mm3": 0
          }
        ]
      }
    ]

  });

  fixture.push({
    //"_id": mongoose.Types.ObjectId("53abae3773b31a0000ec9136"), // Yoav
    "_id": "53abae3773b31a0000ec9136", // Yoav
    "name":"Yoav",
    "sex": "m",
    "dob": "1995-05-25",
    "info": "Yoav loves the color yellow.",
    "availability": [
      {
        "day": "Sun",
        "slots": [
          {
            "hh1": 10,
            "mm1": 30,
            "hh2": 11,
            "mm2": 0
          }
        ]
      },
      {
        "day": "Wed",
        "slots": [
          {
            "hh1": 10,
            "mm1": 30,
            "hh2": 12,
            "mm2": 0
          },
          {
            "hh1": 13,
            "mm1": 0,
            "hh2": 14,
            "mm2": 0,
            "mm3": 0
          }
        ]
      }
    ]

  });

  // an additional example
  //fixture.push({
    //name:'More Test Data',
    //tags:['test','data','more']
  //});


  // mongoose-fixture expects implementor to return
  // the callback passed in context
  return callback(error, fixture);
};
