'use strict';

require('express-mongoose');

/*
 *  File: TeacherSchema.js
 *  Type: Schema
 *  Generated by: Mongoose-Fixture (v0.4.1)
 *
 *
 */

module.exports = function(mongoose, conn){

  var TeacherSchema = mongoose.Schema({
    "name": { type: String, required: true, unique: true },
    "sex": { type: String },
    "dob": { type: Date },
    "age": { type: Number },
    "info": { type: String },
    "image": { type: String },
    "availability": [{
      // TODO
      "day": { type: String },
      "slots": [{
        "timeFrom": { type: Number },
        "timeTo": { type: Number }
      }]
    }],
    "expertise": [{ type: String }]
  });

  TeacherSchema.path('dob').set(function (value) {
    var diff = new Date(Date.now() - Date.parse(value));
    var age = diff.getUTCFullYear() - 1970;
    this.age = age;

    return value;
  });

  TeacherSchema.statics.getAll = function (callback) {
    var promise = new mongoose.Promise();
    if (callback) { promise.addBack(callback); }

    var fields = '_id name sex dob info image availability';
    this.find({}, fields, promise.resolve.bind(promise));
    return promise;
  };

  // mongoose-fixture schemas return this consumable format
  // which allows for you to easily register your models
  // into mongoose/conn
  return { name: 'Teachers', schema: TeacherSchema };
};
